### ISSUE TITLE
MVP dashboard

### ISSUE THREAD

**Issue by zhinu** [dis-moi/analytics#2]
#### Designing the dashboard
1. - [] Design a mockup
2. - [] Get all the data input (v0.1)
3. - [] Choose the appropriate service
4. - [] Create a mvp
5. - [] continuous improvement

(not to forget : include sample data)

**Comment by zhinu** [comment]
In order to have data, automatically pumped into the dashboard, I think the easiest solution would be to pump them directly from mysql tables. This will provoke slowing down (since the amount of data is considerable, and will only grow). So a solution could be to have a backup mysql database where the dashboard would have a daily extract.... (This could be also useful if one day data is lost). 
@JalilArfaoui

**Comment by MaartenLMEM** [comment]
We have currently kind of MVP Dashboard, but not ideal : https://datastudio.google.com/reporting/9d5212b1-9645-4461-80ac-3dee35ca6eb1/page/exbEC/edit
This is enough for now. 
We ll open new issues if they are need not satisfied.
